version: '3.7'
services:
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app   # mount the host folder to the container to change code on the fly
    environment:
      FLASK_ENV: development
      SECRET_MESSAGE: ciao
  redis:
    image: "redis:alpine"
